# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a214e5c46362243275e534fb008b7a9d2df9d8c00a4bc2772ae6de08dd61faff272501ee99566e14cfdbb7df7664fdd172fd2297b1e274d906365bb639c9472

test:
  secret_key_base: f26997801576bc3b0864071616c18a0894e1fd7d9c0995a2db32e858d40f1a047ac0328ef26545b9e7d9e5142b2aae4e7e74881d423ebe98d8bc68763372bc52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
